### ISSUE TITLE
Cannot open some anime

### ISSUE THREAD

**Issue by janydoe** [Semolik/AnimePlayer#2]
When I try opening some anime, I get the following error:

```
JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

Example:
- https://anime.semolik.ru/anidub/anime_ova~10854-blich-vospominaniya-pod-dozhdem-bleach-memories-in-the-rain

**Comment by Semolik** [comment]
The react (main branch) version of the project is no longer supported. I started to rewrite the project and planned to extend the functionality but now I am busy with my [graduation project](/Semolik/music) and don't know when I will continue developing this project, probably not earlier than in half a year.
